version: '3'
services:
    crawler:
        container_name: macshop-tracker
        build:
          context: ./
          dockerfile: Dockerfile
        command: python app.py
        restart: always
        volumes:
          - .:/code
        links:
          - "database:database"
    database:
        image: mongo:4.0
        container_name: mongo4
        ports:
            - "27017:27017"
        volumes:
            - "./data/mongo/data:/data/db"
    backend:
        container_name: flask
        build:
            context: ./flask
            dockerfile: Dockerfile
        command:  python ./flask/app.py
        restart: always
        volumes:
            - .:/flask/code
        ports:
            - "5001:5000"
        links:
          - "database:database"